# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        include_format: false
        default_format: json
    body_listener: true
    format_listener:
       rules:
           - { path: '^/', fallback_format: json, priorities: [ 'json' ] }
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
    param_fetcher_listener: 
        enabled: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
